### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by BMeridian** [jihokoo/passport-delivery.com#1]
Any examples yet??

**Comment by jihokoo** [comment]
i've been waiting on delivery.com to provide user endpoints for the example. what are you trying to do?

**Comment by BMeridian** [comment]
I am not really sure, I am  looking  for simple interface to API -- an
adapter
for deliivery.com not only Oauth......

> Where if I make a API call, the call returns delivery.com info.
> 
> > menus, ratings, price, distance, .....
> 
> not really, users info since thats locked down.

any help?

**Comment by jihokoo** [comment]
okay, so the API is pretty new from what i know and there are no other client libraries.... but let me see if i can help. when you make requests to endpoints to retrieve information specific to a user, you need to include the access token in the Authorization HTTP Header like this:

using the request library...

request.get({
    url: SOME_URL,
    headers: { Authorization: 'Bearer ' + accessToken }
  }, function(err, res, body) {
    console.log(body);
   });

my module will help you get an access token for a specific user. when you are trying to retrieve information such as a list of restaurants that serve mexican food, its not user specific and an access token is not necessary. you also need the access token for a user to make make actions on behalf of  the user. hope this helps.
